export enum AssignmentLanguageEnum {
    TEXT = 'Text',
    JAVASCRIPT = 'JavaScript',
    // TYPESCRIPT = 'TypeScript',
    // PYTHON = 'Python',
    // JAVA = 'Java',
    // C = 'C',
    // C_PLUS_PLUS = 'C++',
    // C_SHARP = 'C#',
    // RUBY = 'Ruby',
    // SWIFT = 'Swift',
    // KOTLIN = 'Kotlin',
    // GO = 'Go',
    // RUST = 'Rust',
    // SCALA = 'Scala',
    // HASKELL = 'Haskell',
    // PERL = 'Perl',
    // PHP = 'PHP',
    // R = 'R',
    // SHELL = 'Shell',
    // SQL = 'SQL',
    // OBJECTIVE_C = 'Objective-C',
    // VISUAL_BASIC = 'Visual Basic',
    // COBOL = 'COBOL',
    // FORTRAN = 'Fortran',
    // DART = 'Dart',
    // ERLANG = 'Erlang',
    // LISP = 'Lisp',
    // MATLAB = 'MATLAB',
    // PASCAL = 'Pascal',
    // PROLOG = 'Prolog',
    // VHDL = 'VHDL',
    // VERILOG = 'Verilog'
}

export enum MaterialTypeEnum {
    VIDEO = 1,
    DOCUMENT,
    QUIZ,
    ASSIGNMENT
}